// Command server runs the voice-survey PoC: a setup page to create a poll from
// a product description (questions generated by a local LLM), a voice page where
// a respondent answers by talking to a local STT+TTS agent, and a results page.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"log"
	"net/http"
	"path/filepath"
	"strings"
	"time"

	"voicesurvey/internal/insight"
	"voicesurvey/internal/llm"
	"voicesurvey/internal/qa"
	"voicesurvey/internal/session"
	"voicesurvey/internal/speech"
	"voicesurvey/internal/ws"
)

func main() {
	addr := flag.String("addr", ":8090", "listen address")
	modelsDir := flag.String("models", "models", "directory with STT/TTS models")
	dataDir := flag.String("data", "data", "directory for poll results")
	webDir := flag.String("web", "web", "directory with static frontend files")
	ollamaModel := flag.String("model", "qwen2.5:3b", "Ollama model for question generation")
	classifyModel := flag.String("classify-model", "", "model for per-turn classification; Ollama or an Anthropic model like claude-sonnet-5 (default: -model). The repair turn fires more on stronger models.")
	insightModel := flag.String("insight-model", "gemma4:latest", "model for the results-insight scoring pass; Ollama (offline) or an Anthropic model like claude-sonnet-5")
	greeting := flag.Bool("greeting", true, "open each session with a short 'how's your day' greeting before the survey")
	agentName := flag.String("agent-name", "Ava", "the voice agent's name (used in the spoken greetings)")
	pacing := flag.Bool("pacing", true, "deliver each question as two beats — a short acknowledgment, a brief pause, then the question — instead of one breath")
	qaFlag := flag.Bool("qa", false, "mount the DEV-ONLY persona QA endpoint (POST /api/qa/reply) for browser E2E testing; never enable in production")
	anthropicEnv := flag.String("anthropic-env", llm.DefaultAnthropicEnvFile(), "file to read ANTHROPIC_API_KEY from if unset in env (for Anthropic classify/insight models)")
	agentModel := flag.String("agent-model", "", "EXPERIMENTAL: run the conversation as an agent loop on this Anthropic model (e.g. claude-sonnet-5) instead of the classifier + state machine. The model calls tools and owns termination. Empty = the production classifier path.")
	flag.Parse()

	log.Println("loading speech models (Kokoro TTS + Whisper STT)…")
	eng, err := speech.NewEngine(*modelsDir)
	if err != nil {
		log.Fatalf("speech engine: %v", err)
	}
	defer eng.Close()

	// Question generation always uses the local Ollama model.
	llmClient, err := llm.New(*ollamaModel)
	if err != nil {
		log.Fatalf("llm: %v", err)
	}

	// The turn classifier is routable: Ollama (incl. :cloud) or Anthropic.
	cm := *classifyModel
	if cm == "" {
		cm = *ollamaModel
	}
	var anthropicKey string
	if llm.IsAnthropicModel(cm) {
		if anthropicKey, err = llm.LoadAnthropicKey(*anthropicEnv); err != nil {
			log.Fatalf("classify model %q: %v", cm, err)
		}
	}
	classifier, err := llm.NewClassifier(cm, anthropicKey)
	if err != nil {
		log.Fatalf("classifier: %v", err)
	}

	// The closing sign-off is written by the SAME model that classifies turns —
	// it's the conversation's "brain", so it also authors the personalized
	// farewell that references what the respondent actually said. One-shot, at
	// end of call, so latency doesn't matter; falls back to a fixed line on error.
	closer, err := llm.NewCompleter(cm, anthropicKey)
	if err != nil {
		log.Fatalf("closing completer: %v", err)
	}

	// The insight scorer is a fully independent one-shot Completer pass, routed
	// the same way (Ollama offline by default, or Anthropic). It never touches
	// the classify/ask path.
	if llm.IsAnthropicModel(*insightModel) && anthropicKey == "" {
		if anthropicKey, err = llm.LoadAnthropicKey(*anthropicEnv); err != nil {
			log.Fatalf("insight model %q: %v", *insightModel, err)
		}
	}
	insightLLM, err := llm.NewCompleter(*insightModel, anthropicKey)
	if err != nil {
		log.Fatalf("insight completer: %v", err)
	}
	// EXPERIMENTAL agent-loop driver. Anthropic-only on purpose: a 3B local model
	// failing to drive a tool loop would say nothing about the architecture, so the
	// comparison runs the alternative on a model capable of doing it justice.
	var agentRunner llm.ToolRunner
	if *agentModel != "" {
		if anthropicKey == "" {
			if anthropicKey, err = llm.LoadAnthropicKey(*anthropicEnv); err != nil {
				log.Fatalf("agent model %q: %v", *agentModel, err)
			}
		}
		if agentRunner, err = llm.NewToolRunner(*agentModel, anthropicKey); err != nil {
			log.Fatalf("agent runner: %v", err)
		}
		log.Printf("EXPERIMENTAL: agent-loop driver active on %s (classifier path bypassed)", *agentModel)
	}

	log.Printf("question-gen model: %s | classify model: %s | insight model: %s", *ollamaModel, cm, *insightModel)

	store, err := session.NewStore(*dataDir)
	if err != nil {
		log.Fatalf("store: %v", err)
	}

	app := &app{store: store, llm: llmClient, webDir: *webDir, insightLLM: insightLLM, insightModel: *insightModel}
	wsHandler := &ws.Handler{Store: store, Speech: eng, LLM: classifier, Closer: closer, Agent: agentRunner, Greeting: *greeting, AgentName: *agentName, Pacing: *pacing, QA: *qaFlag}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /{$}", app.page("index.html"))
	mux.HandleFunc("POST /api/polls", app.createPoll)
	mux.HandleFunc("GET /api/polls/{id}", app.getPoll)
	mux.HandleFunc("GET /api/polls/{id}/insights", app.getInsights)
	mux.HandleFunc("GET /poll/{id}", app.page("poll.html"))
	mux.HandleFunc("GET /results/{id}", app.page("results.html"))
	mux.HandleFunc("GET /insights/{id}", app.page("insights.html"))
	mux.HandleFunc("GET /ws", wsHandler.Serve)
	staticFS := http.FileServer(http.Dir(filepath.Join(*webDir, "static")))
	mux.Handle("GET /static/", http.StripPrefix("/static/", noCache(staticFS)))

	// Dev-only: the persona QA endpoint that generates a simulated respondent's
	// spoken answer on demand (LLM in-character -> TTS in the persona's voice) for
	// browser end-to-end testing. Never mounted in production.
	if *qaFlag {
		mux.HandleFunc("POST /api/qa/reply", qaReply(closer, eng))
		log.Printf("QA persona endpoint ENABLED at POST /api/qa/reply (personas: %s)", qa.PersonaIDs())
	}

	log.Printf("voice-survey PoC listening on http://localhost%s", *addr)
	log.Fatal(http.ListenAndServe(*addr, mux))
}

type app struct {
	store        *session.Store
	llm          *llm.Client
	webDir       string
	insightLLM   llm.Completer
	insightModel string
}

// page serves a static HTML file from the web dir.
func (a *app) page(name string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		http.ServeFile(w, r, filepath.Join(a.webDir, name))
	}
}

// noCache prevents the browser from serving stale JS/CSS — important while
// iterating, so a reload always picks up the latest client.js.
func noCache(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		h.ServeHTTP(w, r)
	})
}

func (a *app) createPoll(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Product string `json:"product"`
		Purpose string `json:"purpose"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || strings.TrimSpace(req.Product) == "" {
		http.Error(w, "missing product", http.StatusBadRequest)
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	plan, err := a.llm.GenerateSurvey(ctx, req.Product, req.Purpose)
	if err != nil {
		log.Printf("question gen failed: %v", err)
		http.Error(w, "could not generate questions", http.StatusBadGateway)
		return
	}
	poll := a.store.Create(req.Product, strings.TrimSpace(req.Purpose), plan.Questions, plan.Intro)
	writeJSON(w, map[string]any{
		"id":        poll.ID,
		"questions": poll.Questions,
		"poll_url":  "/poll/" + poll.ID,
	})
}

func (a *app) getPoll(w http.ResponseWriter, r *http.Request) {
	poll, ok := a.store.GetOrLoad(r.PathValue("id"))
	if !ok {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	writeJSON(w, poll)
}

// getInsights computes (or returns cached) LLM scorings for a poll: product
// sentiment, per-answer usefulness/confidence, and an overall summary. This is
// a separate one-shot LLM pass, independent of the per-turn classifier. Pass
// ?refresh=1 to force recomputation.
func (a *app) getInsights(w http.ResponseWriter, r *http.Request) {
	poll, ok := a.store.GetOrLoad(r.PathValue("id"))
	if !ok {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	if poll.Insights != nil && r.URL.Query().Get("refresh") == "" {
		writeJSON(w, poll.Insights)
		return
	}

	in := insight.Input{Product: poll.Product, EndReason: string(poll.EndReason)}
	if poll.Survey != nil {
		for _, q := range poll.Survey.Questions {
			in.Answers = append(in.Answers, insight.QA{Question: q.Text, Answer: q.Answer, Status: string(q.Status)})
		}
	} else {
		for _, q := range poll.Questions {
			in.Answers = append(in.Answers, insight.QA{Question: q, Status: "unasked"})
		}
	}

	ctx, cancel := context.WithTimeout(r.Context(), 120*time.Second)
	defer cancel()
	res, err := insight.Score(ctx, a.insightLLM, a.insightModel, in)
	if err != nil {
		// Score fails safe (neutral defaults), so we still serve a usable page;
		// just log the reason so it isn't silent.
		log.Printf("insight scoring for %s degraded: %v", poll.ID, err)
	}
	poll.Insights = &res
	a.store.Save(poll)
	writeJSON(w, res)
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}

// qaReply is the DEV-ONLY persona endpoint used by the browser E2E harness. It
// generates a simulated respondent's next spoken turn in character (LLM) and
// returns it as synthesized audio in the persona's voice — which the harness
// plays into the fake microphone, so the answer then flows back through the real
// VAD -> STT -> classifier path. The generated text is echoed in X-QA-Text for
// logging. It reuses the classify-model completer, so nothing extra is wired.
func qaReply(gen llm.Completer, eng *speech.Engine) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req struct {
			Persona  string `json:"persona"`
			Question string `json:"question"`
			Answered int    `json:"answered"`
		}
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, "bad request", http.StatusBadRequest)
			return
		}
		p, ok := qa.Find(req.Persona)
		if !ok {
			http.Error(w, "unknown persona", http.StatusBadRequest)
			return
		}
		ctx, cancel := context.WithTimeout(r.Context(), 30*time.Second)
		defer cancel()
		text, err := gen.Complete(ctx, p.System, qa.ReplyUser(req.Question, req.Answered))
		if err != nil {
			http.Error(w, "generation failed: "+err.Error(), http.StatusBadGateway)
			return
		}
		text = strings.TrimSpace(strings.Trim(strings.TrimSpace(text), `"`))
		wav, err := eng.SynthesizeVoice(text, p.VoiceID)
		if err != nil {
			http.Error(w, "tts failed: "+err.Error(), http.StatusBadGateway)
			return
		}
		w.Header().Set("Content-Type", "audio/wav")
		w.Header().Set("X-QA-Text", strings.ReplaceAll(text, "\n", " "))
		w.Header().Set("Access-Control-Expose-Headers", "X-QA-Text")
		_, _ = w.Write(wav)
	}
}
