// Command server runs the voice-survey PoC: a setup page to create a poll from
// a product description (questions generated by a local LLM), a voice page where
// a respondent answers by talking to a local STT+TTS agent, and a results page.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"log"
	"net/http"
	"path/filepath"
	"strings"
	"time"

	"voicesurvey/internal/llm"
	"voicesurvey/internal/session"
	"voicesurvey/internal/speech"
	"voicesurvey/internal/ws"
)

func main() {
	addr := flag.String("addr", ":8090", "listen address")
	modelsDir := flag.String("models", "models", "directory with STT/TTS models")
	dataDir := flag.String("data", "data", "directory for poll results")
	webDir := flag.String("web", "web", "directory with static frontend files")
	ollamaModel := flag.String("model", "qwen2.5:3b", "Ollama model for question generation")
	flag.Parse()

	log.Println("loading speech models (Kokoro TTS + Whisper STT)…")
	eng, err := speech.NewEngine(*modelsDir)
	if err != nil {
		log.Fatalf("speech engine: %v", err)
	}
	defer eng.Close()

	llmClient, err := llm.New(*ollamaModel)
	if err != nil {
		log.Fatalf("llm: %v", err)
	}

	store, err := session.NewStore(*dataDir)
	if err != nil {
		log.Fatalf("store: %v", err)
	}

	app := &app{store: store, llm: llmClient, webDir: *webDir}
	wsHandler := &ws.Handler{Store: store, Speech: eng, LLM: llmClient}

	mux := http.NewServeMux()
	mux.HandleFunc("GET /{$}", app.page("index.html"))
	mux.HandleFunc("POST /api/polls", app.createPoll)
	mux.HandleFunc("GET /api/polls/{id}", app.getPoll)
	mux.HandleFunc("GET /poll/{id}", app.page("poll.html"))
	mux.HandleFunc("GET /results/{id}", app.page("results.html"))
	mux.HandleFunc("GET /ws", wsHandler.Serve)
	staticFS := http.FileServer(http.Dir(filepath.Join(*webDir, "static")))
	mux.Handle("GET /static/", http.StripPrefix("/static/", noCache(staticFS)))

	log.Printf("voice-survey PoC listening on http://localhost%s", *addr)
	log.Fatal(http.ListenAndServe(*addr, mux))
}

type app struct {
	store  *session.Store
	llm    *llm.Client
	webDir string
}

// page serves a static HTML file from the web dir.
func (a *app) page(name string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		http.ServeFile(w, r, filepath.Join(a.webDir, name))
	}
}

// noCache prevents the browser from serving stale JS/CSS — important while
// iterating, so a reload always picks up the latest client.js.
func noCache(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		h.ServeHTTP(w, r)
	})
}

func (a *app) createPoll(w http.ResponseWriter, r *http.Request) {
	var req struct {
		Product string `json:"product"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || strings.TrimSpace(req.Product) == "" {
		http.Error(w, "missing product", http.StatusBadRequest)
		return
	}
	ctx, cancel := context.WithTimeout(r.Context(), 60*time.Second)
	defer cancel()

	questions, err := a.llm.GenerateQuestions(ctx, req.Product)
	if err != nil {
		log.Printf("question gen failed: %v", err)
		http.Error(w, "could not generate questions", http.StatusBadGateway)
		return
	}
	poll := a.store.Create(req.Product, questions)
	writeJSON(w, map[string]any{
		"id":        poll.ID,
		"questions": poll.Questions,
		"poll_url":  "/poll/" + poll.ID,
	})
}

func (a *app) getPoll(w http.ResponseWriter, r *http.Request) {
	poll, ok := a.store.Get(r.PathValue("id"))
	if !ok {
		http.Error(w, "not found", http.StatusNotFound)
		return
	}
	writeJSON(w, poll)
}

func writeJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(v)
}
